---

- name: Install pip_extra_packages
  openbsd_pkg:
    name: "{{ pip_extra_packages }}"
  when:
    - pip_extra_packages | length > 0

- name: Install pip_packages
  openbsd_pkg:
    name: "{{ pip_packages }}"
    state: present

- name: Create symlink to pip
  ansible.builtin.file:

    # XXX it seems like many asumes the pip for python version x.y.z is named
    # 'pip${x}'. ansible.builtin.pip is one of them
    dest: "/usr/local/bin/pip{{ ansible_python['version']['major'] }}"
    src: "{{ pip_executable_file }}"
    state: link
