---

- name: Install pip_extra_packages
  apt:
    name: "{{ pip_extra_packages }}"
  when:
    - pip_extra_packages | length > 0

- name: Install pip_packages
  apt:
    name: "{{ pip_packages }}"
    state: present
