---
# tasks file for ansible-role-pip

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific install tasks
  include: "install-{{ ansible_os_family }}.yml"
